USE master;   
GO    
  
CREATE ASYMMETRIC KEY SQLCLRTestKey FROM EXECUTABLE FILE = 'RowLevelAuditServer.dll';
GO

CREATE LOGIN SQLCLRTestLogin FROM ASYMMETRIC KEY SQLCLRTestKey;
GO

GRANT EXTERNAL ACCESS ASSEMBLY TO SQLCLRTestLogin;   
GO

